---

# Install packages
- name: Install packages
  become: yes
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - nginx


# Create virtual host
- name: Create Nginx Virtual Host
  become: yes
  template: 
    src: vhost.j2
    dest: /etc/nginx/sites-available/{{ project_name }}
    force: yes


# Enable virtual host
- name: Enable virtual host
  become: yes
  file: 
    src: /etc/nginx/sites-available/{{ project_name }}
    dest: /etc/nginx/sites-enabled/{{ project_name }}
    state: link
  notify:
    - restart-nginx


# Disable default vhost
- name: Disable default virtual host
  become: yes
  file:
    dest: /etc/nginx/sites-enabled/default
    state: absent
  notify:
    - restart-nginx


# Create index page
- name: Create index.html page
  become: yes
  template:
    src: index.html.j2
    dest: "{{ web_root }}/index.html"

